/** AUTO-GENERATED — npm run prepare:public-screenshots */
window.__SCREENSHOT_MANIFEST__ = [
  {
    "id": "location-access-en",
    "category": "settings",
    "language": "English",
    "title": "Location access control",
    "caption": "Foreground-only location footprints with clear permission copy.",
    "alt": "Vyaamikk Diary Business Footprint screen explaining optional location access",
    "showcaseSection": "settings-privacy",
    "safeForPublic": true,
    "src": "assets/screenshots/location-access-en.webp",
    "src2x": "assets/screenshots/location-access-en@2x.webp",
    "fallback": "assets/screenshots/location-access-en.png",
    "fallback2x": "assets/screenshots/location-access-en@2x.png",
    "width": 430,
    "width2x": 860
  },
  {
    "id": "dashboard-en",
    "category": "dashboard",
    "language": "English",
    "title": "Your business dashboard",
    "caption": "A clean daily workspace for records, drafts and insights.",
    "alt": "Vyaamikk Diary You dashboard in English with search and at-a-glance summaries",
    "showcaseSection": "daily-workspace",
    "safeForPublic": false,
    "src": "assets/screenshots/dashboard-en.webp",
    "src2x": "assets/screenshots/dashboard-en@2x.webp",
    "fallback": "assets/screenshots/dashboard-en.png",
    "fallback2x": "assets/screenshots/dashboard-en@2x.png",
    "width": 430,
    "width2x": 860,
    "privacyNote": "Contains demo profile name and registered company name — exclude until redacted or approved."
  },
  {
    "id": "dashboard-hi",
    "category": "dashboard",
    "language": "Hindi",
    "title": "व्यवसाय डैशबोर्ड",
    "caption": "रिकॉर्ड, ड्राफ्ट और जानकारी के लिए साफ़ दैनिक कार्यक्षेत्र।",
    "alt": "Vyaamikk Diary dashboard in Hindi showing business profile and record summaries",
    "showcaseSection": "multilingual",
    "safeForPublic": false,
    "src": "assets/screenshots/dashboard-hi.webp",
    "src2x": "assets/screenshots/dashboard-hi@2x.webp",
    "fallback": "assets/screenshots/dashboard-hi.png",
    "fallback2x": "assets/screenshots/dashboard-hi@2x.png",
    "width": 430,
    "width2x": 860,
    "privacyNote": "Contains demo profile name and registered company name — exclude until redacted or approved."
  },
  {
    "id": "dashboard-ta",
    "category": "dashboard",
    "language": "Tamil",
    "title": "வணிக டாஷ்போர்டு",
    "caption": "பதிவுகள், வரைவுகள் மற்றும் நுண்ணறிவுகளுக்கான தினசரி பணிமனை.",
    "alt": "Vyaamikk Diary dashboard in Tamil with multilingual navigation",
    "showcaseSection": "multilingual",
    "safeForPublic": false,
    "src": "assets/screenshots/dashboard-ta.webp",
    "src2x": "assets/screenshots/dashboard-ta@2x.webp",
    "fallback": "assets/screenshots/dashboard-ta.png",
    "fallback2x": "assets/screenshots/dashboard-ta@2x.png",
    "width": 430,
    "width2x": 860,
    "privacyNote": "Contains demo profile name and registered company name — exclude until redacted or approved."
  },
  {
    "id": "dashboard-te",
    "category": "dashboard",
    "language": "Telugu",
    "title": "వ్యాపార డాష్‌బోర్డ్",
    "caption": "రికార్డులు, డ్రాఫ్ట్‌లు మరియు ఇన్‌సైట్‌ల కోసం స్వచ్ఛమైన రోజువారీ వర్క్‌స్పేస్.",
    "alt": "Vyaamikk Diary dashboard in Telugu with at-a-glance record tiles",
    "showcaseSection": "multilingual",
    "safeForPublic": false,
    "src": "assets/screenshots/dashboard-te.webp",
    "src2x": "assets/screenshots/dashboard-te@2x.webp",
    "fallback": "assets/screenshots/dashboard-te.png",
    "fallback2x": "assets/screenshots/dashboard-te@2x.png",
    "width": 430,
    "width2x": 860,
    "privacyNote": "Contains demo profile name and registered company name — exclude until redacted or approved."
  },
  {
    "id": "dashboard-gu",
    "category": "dashboard",
    "language": "Gujarati",
    "title": "વ્યવસાય ડેશબોર્ડ",
    "caption": "રેકોર્ડ, ડ્રાફ્ટ અને ઇનસાઇટ માટે સ્વચ્છ દૈનિક વર્કસ્પેસ.",
    "alt": "Vyaamikk Diary dashboard in Gujarati with business identity card",
    "showcaseSection": "multilingual",
    "safeForPublic": false,
    "src": "assets/screenshots/dashboard-gu.webp",
    "src2x": "assets/screenshots/dashboard-gu@2x.webp",
    "fallback": "assets/screenshots/dashboard-gu.png",
    "fallback2x": "assets/screenshots/dashboard-gu@2x.png",
    "width": 430,
    "width2x": 860,
    "privacyNote": "Contains demo profile name and registered company name — exclude until redacted or approved."
  },
  {
    "id": "new-record-gu",
    "category": "new-record",
    "language": "Gujarati",
    "title": "નવો રેકોર્ડ",
    "caption": "ચુકવણી, દુકાન, PO અને દસ્તાવેજ — એક જ સંગ્રહિત મેનુ.",
    "alt": "Vyaamikk Diary new record menu in Gujarati listing payment, Dukaan and purchase order types",
    "showcaseSection": "multilingual",
    "safeForPublic": true,
    "src": "assets/screenshots/new-record-gu.webp",
    "src2x": "assets/screenshots/new-record-gu@2x.webp",
    "fallback": "assets/screenshots/new-record-gu.png",
    "fallback2x": "assets/screenshots/new-record-gu@2x.png",
    "width": 430,
    "width2x": 860
  },
  {
    "id": "new-record-en",
    "category": "new-record",
    "language": "English",
    "title": "New record hub",
    "caption": "Payment requests, Dukaan, purchase orders, movement and documents in one place.",
    "alt": "Vyaamikk Diary new record selection screen in English",
    "showcaseSection": "business-records",
    "safeForPublic": true,
    "src": "assets/screenshots/new-record-en.webp",
    "src2x": "assets/screenshots/new-record-en@2x.webp",
    "fallback": "assets/screenshots/new-record-en.png",
    "fallback2x": "assets/screenshots/new-record-en@2x.png",
    "width": 430,
    "width2x": 860
  },
  {
    "id": "new-record-hi",
    "category": "new-record",
    "language": "Hindi",
    "title": "नया रिकॉर्ड",
    "caption": "भुगतान, दुकान, PO और दस्तावेज़ — एक संरचित मेनू।",
    "alt": "Vyaamikk Diary new record menu in Hindi with business record categories",
    "showcaseSection": "multilingual",
    "safeForPublic": true,
    "src": "assets/screenshots/new-record-hi.webp",
    "src2x": "assets/screenshots/new-record-hi@2x.webp",
    "fallback": "assets/screenshots/new-record-hi.png",
    "fallback2x": "assets/screenshots/new-record-hi@2x.png",
    "width": 430,
    "width2x": 860
  },
  {
    "id": "new-record-te",
    "category": "new-record",
    "language": "Telugu",
    "title": "కొత్త రికార్డు",
    "caption": "చెల్లింపు, దుకాణం, PO మరియు పత్రాలు — ఒకే మెనూ.",
    "alt": "Vyaamikk Diary new record menu in Telugu",
    "showcaseSection": "multilingual",
    "safeForPublic": true,
    "src": "assets/screenshots/new-record-te.webp",
    "src2x": "assets/screenshots/new-record-te@2x.webp",
    "fallback": "assets/screenshots/new-record-te.png",
    "fallback2x": "assets/screenshots/new-record-te@2x.png",
    "width": 430,
    "width2x": 860
  },
  {
    "id": "statutory-info-en",
    "category": "statutory",
    "language": "English",
    "title": "Statutory information",
    "caption": "Informational GST, Income Tax and compliance due-date prompts.",
    "alt": "Vyaamikk Diary Statutory Information screen with GST and Income Tax filters",
    "showcaseSection": "daily-workspace",
    "safeForPublic": true,
    "src": "assets/screenshots/statutory-info-en.webp",
    "src2x": "assets/screenshots/statutory-info-en@2x.webp",
    "fallback": "assets/screenshots/statutory-info-en.png",
    "fallback2x": "assets/screenshots/statutory-info-en@2x.png",
    "width": 430,
    "width2x": 860
  }
];
