/**
 * Copy src/goodsEvidence domain into functions/src/goodsEvidence.
 * Single source: do not hand-duplicate canonical/validate/command rules.
 * Rewrites client sha256 to Node crypto. Does not lift functions rootDir.
 *
 * Run: npx tsx tools/goods-evidence-emulator/packageFunctionsGoodsEvidence.ts
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "../..");
const sourceDir = join(repoRoot, "src/goodsEvidence");
const destDir = join(repoRoot, "functions/src/goodsEvidence");

const DOMAIN_FILES = [
  "canonical.ts",
  "constants.ts",
  "time.ts",
  "grinNumber.ts",
  "validate.ts",
  "quantities.ts",
  "types.ts",
  "ewb.ts",
  "snapshot.ts",
  "custody.ts",
  "command.ts",
  "hashChain.ts",
  "ports.ts",
] as const;

const GENERATED_HEADER =
  "/** GENERATED by tools/goods-evidence-emulator/packageFunctionsGoodsEvidence.ts — do not hand-edit. */\n";

const HASH_NODE = `${GENERATED_HEADER}
import { createHash } from "node:crypto";

/** Node SHA-256. Not the client hash helper. Not Expo. */
export function sha256Hex(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}
`;

const FORBIDDEN = [
  /from ["']react["']/,
  /from ["']react-native["']/,
  /from ["']@\//,
  /from ["']expo/,
  /localDb/,
  /EXPO_PUBLIC_GOODS_EVIDENCE_ENABLED/,
  /isGoodsEvidenceEnabled/,
];

const KEEP = new Set(["callables.ts", "README.md"]);

function rewrite(src: string): string {
  return src.replace(/from ["']@\/utils\/sha256Hex["']/g, 'from "./hashNode"');
}

function assertSafe(file: string, src: string): void {
  for (const pattern of FORBIDDEN) {
    if (pattern.test(src)) {
      throw new Error(`${file} is not safe to package: matches ${pattern}`);
    }
  }
}

function main(): void {
  mkdirSync(destDir, { recursive: true });
  for (const name of readdirSync(destDir)) {
    if (KEEP.has(name)) continue;
    rmSync(join(destDir, name), { recursive: true, force: true });
  }

  writeFileSync(join(destDir, "hashNode.ts"), HASH_NODE);

  for (const name of DOMAIN_FILES) {
    const raw = readFileSync(join(sourceDir, name), "utf8");
    const rewritten = rewrite(raw);
    const body = rewritten.startsWith("/** GENERATED")
      ? rewritten
      : `${GENERATED_HEADER}${rewritten}`;
    assertSafe(name, body);
    writeFileSync(join(destDir, name), body);
  }

  writeFileSync(
    join(destDir, "generated.manifest.json"),
    `${JSON.stringify({ source: "src/goodsEvidence", files: [...DOMAIN_FILES, "hashNode.ts"] }, null, 2)}\n`
  );
}

main();
