/**
 * Copy src/goodsEvidence domain into functions/src/goodsEvidence.
 * Single source: do not hand-duplicate canonical/validate/command rules.
 * Rewrites client sha256 to Node crypto. Does not lift functions rootDir.
 *
 * Run: npx tsx tools/goods-evidence-emulator/packageFunctionsGoodsEvidence.ts
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "../..");
const sourceDir = join(repoRoot, "src/goodsEvidence");
const destDir = join(repoRoot, "functions/src/goodsEvidence");

export const DOMAIN_FILES = [
  "canonical.ts",
  "constants.ts",
  "time.ts",
  "grinNumber.ts",
  "validate.ts",
  "quantities.ts",
  "types.ts",
  "ewb.ts",
  "snapshot.ts",
  "custody.ts",
  "command.ts",
  "hashChain.ts",
  "ports.ts",
  "evidence.ts",
] as const;

export const GENERATED_HEADER =
  "/** GENERATED by tools/goods-evidence-emulator/packageFunctionsGoodsEvidence.ts — do not hand-edit. */\n";

export const HASH_NODE = `${GENERATED_HEADER}
import { createHash } from "node:crypto";

/** Node SHA-256. Not the client hash helper. Not Expo. */
export function sha256Hex(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}
`;

const FORBIDDEN = [
  /from ["']react["']/,
  /from ["']react-native["']/,
  /from ["']@\//,
  /from ["']expo/,
  /localDb/,
  /EXPO_PUBLIC_GOODS_EVIDENCE_ENABLED/,
  /isGoodsEvidenceEnabled/,
];

export const KEEP = new Set(["callables.ts", "composed.ts", "README.md"]);

export function rewrite(src: string): string {
  return src.replace(/from ["']@\/utils\/sha256Hex["']/g, 'from "./hashNode"');
}

export function expectedGeneratedSource(_fileName: string, raw: string): string {
  const rewritten = rewrite(raw);
  return rewritten.startsWith("/** GENERATED") ? rewritten : `${GENERATED_HEADER}${rewritten}`;
}

function assertSafe(file: string, src: string): void {
  for (const pattern of FORBIDDEN) {
    if (pattern.test(src)) {
      throw new Error(`${file} is not safe to package: matches ${pattern}`);
    }
  }
}

export function packageFunctionsGoodsEvidence(options?: {
  sourceDir?: string;
  destDir?: string;
}): void {
  const fromDir = options?.sourceDir ?? sourceDir;
  const toDir = options?.destDir ?? destDir;
  mkdirSync(toDir, { recursive: true });
  for (const name of readdirSync(toDir)) {
    if (KEEP.has(name)) continue;
    rmSync(join(toDir, name), { recursive: true, force: true });
  }

  writeFileSync(join(toDir, "hashNode.ts"), HASH_NODE);

  for (const name of DOMAIN_FILES) {
    const raw = readFileSync(join(fromDir, name), "utf8");
    const body = expectedGeneratedSource(name, raw);
    assertSafe(name, body);
    writeFileSync(join(toDir, name), body);
  }

  writeFileSync(
    join(toDir, "generated.manifest.json"),
    `${JSON.stringify({ source: "src/goodsEvidence", files: [...DOMAIN_FILES, "hashNode.ts"] }, null, 2)}\n`
  );
}

function isExecutedDirectly(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  return fileURLToPath(import.meta.url) === resolve(entry);
}

if (isExecutedDirectly()) {
  packageFunctionsGoodsEvidence();
}
