/** GENERATED by tools/goods-evidence-emulator/packageFunctionsGoodsEvidence.ts — do not hand-edit. */
/**
 * G1/G4 durable register, reconcile, and mutation adapter (emulator).
 *
 * Not a live callable. Do not import this adapter into the production Functions entrypoint.
 * Does not import client runtime, React, @/config, localDb, or @/utils/sha256Hex.
 *
 * Trusted identity is the authenticated uid. InMemoryGoodsLedger is not this backend.
 */

import { GOODS_EVIDENCE_SCHEMA_VERSION } from "../constants";
import {
  MUTATION_COMMAND_TYPES,
  type AmendFieldsBody,
  type CorrectReturnDispatchBody,
  type DispatchReturnBody,
  type LinkVerifiedEvidenceBody,
  type MutationCommandType,
  type RecordEwbObservationBody,
  type RecordQcBody,
  type RegisterGoodsReceiptBody,
  type VoidWithReasonBody,
} from "../command";
import { derivePhysicalCustody } from "../custody";
import { emptyEwbHistories } from "../ewb";
import { formatGrinNumber } from "../grinNumber";
import {
  emptyLedgers,
  type LineQuantityLedgers,
} from "../quantities";
import { cloneSnapshot } from "../snapshot";
import { financialYearTokenForIstInstant, formatUtcIso } from "../time";
import type { GrinConfirmedProjection, GrinReceiptReadResult } from "../ports";
import type { GrinEvent, GrinView, ImmutableGrin } from "../types";
import {
  commandEnvelopeError,
  commandReasonError,
  effectiveRecordError,
  linkVerifiedEvidenceBodyError,
  mutationBodyError,
  recordEwbObservationBodyError,
  registerBodyError,
  verifiedEvidenceIdentityError,
} from "../validate";
import { freezeDigest, hashEventEnvelope, hashOriginalSnapshot } from "./hash";
import { commandIdError, documentIdError, lineIdError } from "./ids";
import {
  envelopeByteError,
  extraEnvelopeKeyError,
  extraReadKeyError,
  extraReconcileKeyError,
  inputShapeError,
  lineCountError,
  normalizeJsonCopy,
  serverFieldError,
  sparseArrayError,
  textLimitError,
} from "./limits";
import { logG1 } from "./log";
import {
  applyAmendFields,
  applyCorrectReturnDispatch,
  applyDispatchReturn,
  applyLinkVerifiedEvidence,
  applyRecordEwbObservation,
  applyRecordQc,
  applyVoidWithReason,
  hydrateReceipt,
  persistableReceipt,
  type PersistedReceipt,
} from "./mutations";
import {
  admissionPath,
  commandPath,
  eventPath,
  eventsCollectionPath,
  ledgerPath,
  receiptPath,
  serialPath,
  userPath,
} from "./paths";
import { isRetryable } from "./retry";
import { allocateFromCounter } from "./serial";
import type {
  AdmissionPolicy,
  G1Clock,
  G1CommandResult,
  G1Deny,
  G1DocSnap,
  G1Firestore,
  G1Hooks,
  G1MutationCommandType,
  G1MutationResult,
  G1MutationSuccess,
  G1ReconcileResult,
  G1RegisterResult,
  G1RegisterSuccess,
  G1Transaction,
  TrustedCaller,
} from "./types";

export { isRetryable };

const GENERIC_DENY = "denied";
const MAX_TX_ATTEMPTS = 5;

const ABSENT_SNAP: G1DocSnap = {
  exists: false,
  data: () => undefined,
};

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return value != null && typeof value === "object" && !Array.isArray(value);
}

/** Safe ledger id for path reads. Does not mutate caller input or validate the rest of the body. */
function peekLedgerId(input: unknown): string | null {
  if (!isPlainObject(input)) return null;
  if (documentIdError("ledgerId", input.ledgerId)) return null;
  return input.ledgerId as string;
}

function deny(code: G1Deny["code"], detail: string): G1Deny {
  logG1("grin_g1_denied", { code });
  return { ok: false, code, detail };
}

function parsePolicy(data: Record<string, unknown> | undefined): AdmissionPolicy | null {
  if (!data) return null;
  if (data.schemaVersion !== 1) return null;
  if (data.newCommands !== "allow" && data.newCommands !== "deny") return null;
  if (data.reconciliation !== "allow" && data.reconciliation !== "deny") return null;
  return {
    schemaVersion: 1,
    newCommands: data.newCommands,
    reconciliation: data.reconciliation,
  };
}

function storedSuccess(data: Record<string, unknown> | undefined): G1RegisterSuccess | null {
  const result = data?.result;
  if (!isPlainObject(result)) return null;
  if (result.ok !== true) return null;
  if (typeof result.receiptId !== "string") return null;
  if (typeof result.issuedNumber !== "string") return null;
  if (typeof result.serial !== "number") return null;
  if (typeof result.serverRegisteredAtUtc !== "string") return null;
  if (typeof result.eventVersion !== "number") return null;
  if (typeof result.headHash !== "string") return null;
  return {
    ok: true,
    replayed: true,
    receiptId: result.receiptId,
    issuedNumber: result.issuedNumber,
    serial: result.serial,
    serverRegisteredAtUtc: result.serverRegisteredAtUtc,
    eventVersion: result.eventVersion,
    headHash: result.headHash,
  };
}

function mutationCommandTypeOf(value: unknown): G1MutationCommandType | null {
  if (typeof value !== "string") return null;
  for (const type of MUTATION_COMMAND_TYPES) {
    if (type === value) return type;
  }
  return null;
}

function hydrateStoredEvent(data: Record<string, unknown> | undefined): GrinEvent | null {
  if (!data) return null;
  if (data.schemaVersion !== GOODS_EVIDENCE_SCHEMA_VERSION) return null;
  if (typeof data.eventId !== "string" || data.eventId.length === 0) return null;
  if (typeof data.receiptId !== "string" || data.receiptId.length === 0) return null;
  if (typeof data.streamSequence !== "number" || !Number.isInteger(data.streamSequence) || data.streamSequence < 1) {
    return null;
  }
  if (typeof data.type !== "string" || data.type.length === 0) return null;
  if (typeof data.actorUid !== "string" || data.actorUid.length === 0) return null;
  if (typeof data.serverAcceptedAtUtc !== "string") return null;
  if (typeof data.clientObservedAtUtc !== "string") return null;
  if (typeof data.reason !== "string") return null;
  if (
    typeof data.expectedPreviousVersion !== "number" ||
    !Number.isInteger(data.expectedPreviousVersion) ||
    data.expectedPreviousVersion < 0
  ) {
    return null;
  }
  if (!isPlainObject(data.typedChanges)) return null;
  if (data.previousHash !== null && typeof data.previousHash !== "string") return null;
  if (typeof data.eventHash !== "string" || data.eventHash.length === 0) return null;
  if (data.firestoreCommitTime !== null && typeof data.firestoreCommitTime !== "string") return null;
  return {
    schemaVersion: GOODS_EVIDENCE_SCHEMA_VERSION,
    eventId: data.eventId,
    receiptId: data.receiptId,
    streamSequence: data.streamSequence,
    type: data.type as GrinEvent["type"],
    actorUid: data.actorUid,
    serverAcceptedAtUtc: data.serverAcceptedAtUtc,
    clientObservedAtUtc: data.clientObservedAtUtc,
    reason: data.reason,
    expectedPreviousVersion: data.expectedPreviousVersion,
    typedChanges: data.typedChanges,
    previousHash: data.previousHash,
    eventHash: data.eventHash,
    firestoreCommitTime: data.firestoreCommitTime,
  };
}

function assembleConfirmed(
  receipt: PersistedReceipt,
  events: GrinEvent[],
  receiptId: string
): GrinConfirmedProjection | null {
  if (typeof receipt.view.eventVersion !== "number" || !Number.isInteger(receipt.view.eventVersion)) {
    return null;
  }
  if (receipt.view.eventVersion < 1) return null;
  if (typeof receipt.view.headHash !== "string" || receipt.view.headHash.length === 0) return null;
  if (receipt.original.receiptId !== receiptId || receipt.effective.receiptId !== receiptId) return null;
  const ordered = [...events].sort((a, b) => a.streamSequence - b.streamSequence);
  if (ordered.length !== receipt.view.eventVersion) return null;
  for (let i = 0; i < ordered.length; i++) {
    const event = ordered[i]!;
    if (event.streamSequence !== i + 1) return null;
    if (event.receiptId !== receiptId) return null;
  }
  const head = ordered[ordered.length - 1];
  if (!head || head.eventHash !== receipt.view.headHash) return null;
  return {
    receiptId,
    eventVersion: receipt.view.eventVersion,
    headHash: receipt.view.headHash,
    original: cloneSnapshot(receipt.original),
    events: ordered.map((event) => cloneSnapshot(event)),
    effective: cloneSnapshot(receipt.effective),
  };
}

function storedMutationSuccess(data: Record<string, unknown> | undefined): G1MutationSuccess | null {
  const result = data?.result;
  if (!isPlainObject(result)) return null;
  if (result.ok !== true) return null;
  if (typeof result.issuedNumber === "string") return null;
  if (typeof result.receiptId !== "string") return null;
  if (typeof result.eventId !== "string") return null;
  if (typeof result.eventVersion !== "number") return null;
  if (typeof result.headHash !== "string") return null;
  if (typeof result.serverAcceptedAtUtc !== "string") return null;
  return {
    ok: true,
    replayed: true,
    receiptId: result.receiptId,
    eventId: result.eventId,
    eventVersion: result.eventVersion,
    headHash: result.headHash,
    serverAcceptedAtUtc: result.serverAcceptedAtUtc,
  };
}

type FrozenRegister = {
  commandId: string;
  type: "registerGoodsReceipt";
  ownerUid: string;
  ledgerId: string;
  body: RegisterGoodsReceiptBody;
  digest: string;
};

type FrozenMutation = {
  commandId: string;
  type: MutationCommandType;
  ownerUid: string;
  ledgerId: string;
  body: unknown;
  digest: string;
};

type IssuedBuild = {
  original: ImmutableGrin;
  event: GrinEvent;
  view: GrinView;
  lineLedgers: Record<string, LineQuantityLedgers>;
  result: G1RegisterSuccess;
};

export class GoodsEvidenceRegisterAdapter {
  constructor(
    private readonly db: G1Firestore,
    private readonly clock: G1Clock,
    private readonly hooks: G1Hooks = {}
  ) {}

  async register(caller: TrustedCaller, envelope: unknown): Promise<G1RegisterResult> {
    if (!caller.uid) return deny("unauthenticated", GENERIC_DENY);
    const uid = caller.uid;

    return this.runAttempts(async (tx, attempt) => {
      const scope = await this.readAdmissionScope(tx, uid, envelope);
      const gate = this.gate(
        scope.admissionSnap.data(),
        scope.userSnap.exists,
        scope.userSnap.data(),
        { peeked: scope.ledgerPeeked, exists: scope.ledgerSnap.exists, data: scope.ledgerSnap.data() },
        uid
      );
      if (!gate.ok) return gate;
      if (gate.policy.newCommands !== "allow") return deny("policy_denied", GENERIC_DENY);

      const prepared = this.prepareRegister(envelope, uid);
      if (!prepared.ok) return prepared;
      const frozen = prepared.frozen;

      const serverMs = this.clock.nowMs();
      const fyToken = financialYearTokenForIstInstant(serverMs);
      const commandRef = this.db.doc(commandPath(uid, frozen.ledgerId, frozen.commandId));
      const commandSnap = await tx.get(commandRef);
      const receiptRef = this.db.doc(receiptPath(uid, frozen.ledgerId, frozen.body.receiptId));
      const receiptSnap = await tx.get(receiptRef);
      const serialRef = this.db.doc(serialPath(uid, frozen.ledgerId, fyToken));
      const serialSnap = await tx.get(serialRef);
      await this.hooks.afterReads?.(attempt);

      if (commandSnap.exists) {
        const stored = commandSnap.data();
        if (stored?.digest !== frozen.digest) {
          return deny("digest_conflict", "same commandId with a different body");
        }
        const result = storedSuccess(stored);
        if (!result) return deny("digest_conflict", "commandId is not a register command");
        logG1("grin_g1_replayed", { replayed: true, attempt });
        return result;
      }

      if (receiptSnap.exists) {
        return deny("receipt_exists", "receipt already issued; history cannot be replaced");
      }

      const allocated = allocateFromCounter(serialSnap.exists, serialSnap.data(), fyToken);
      if (!allocated.ok) return deny(allocated.code, GENERIC_DENY);
      const serial = allocated.serial;
      const issued = this.buildIssued(frozen, uid, serverMs, fyToken, serial);
      if (!("result" in issued)) return issued;

      tx.set(serialRef, {
        fyToken,
        nextSerial: serial + 1,
        lastIssuedSerial: serial,
      });
      tx.set(receiptRef, {
        original: issued.original,
        effective: cloneSnapshot(issued.original),
        view: issued.view,
        lineLedgers: issued.lineLedgers,
        ewbHistories: emptyEwbHistories(),
        returnDispatches: Object.create(null),
        linkedEvidence: [],
      });
      tx.set(
        this.db.doc(eventPath(uid, frozen.ledgerId, issued.original.receiptId, issued.event.eventId)),
        { ...issued.event }
      );
      tx.set(commandRef, {
        schemaVersion: GOODS_EVIDENCE_SCHEMA_VERSION,
        ownerUid: uid,
        ledgerId: frozen.ledgerId,
        commandId: frozen.commandId,
        type: "registerGoodsReceipt",
        digest: frozen.digest,
        receiptId: issued.original.receiptId,
        result: { ...issued.result, replayed: false },
      });
      return issued.result;
    });
  }

  async reconcile(caller: TrustedCaller, input: unknown): Promise<G1ReconcileResult> {
    if (!caller.uid) return deny("unauthenticated", GENERIC_DENY);
    const uid = caller.uid;

    return this.runAttempts(async (tx, attempt) => {
      const scope = await this.readAdmissionScope(tx, uid, input);
      const gate = this.gate(
        scope.admissionSnap.data(),
        scope.userSnap.exists,
        scope.userSnap.data(),
        { peeked: scope.ledgerPeeked, exists: scope.ledgerSnap.exists, data: scope.ledgerSnap.data() },
        uid
      );
      if (!gate.ok) return gate;
      if (gate.policy.reconciliation !== "allow") return deny("policy_denied", GENERIC_DENY);

      const prepared = this.prepareReconcile(input);
      if (!prepared.ok) return prepared;
      const commandSnap = await tx.get(this.db.doc(commandPath(uid, prepared.ledgerId, prepared.commandId)));
      await this.hooks.afterReads?.(attempt);

      if (!commandSnap.exists) return deny("not_found", "command not found");
      const stored = commandSnap.data();
      const registerResult = storedSuccess(stored);
      if (registerResult) {
        if (stored?.type !== "registerGoodsReceipt") return deny("not_found", "command not found");
        logG1("grin_g1_replayed", { replayed: true, attempt });
        return { ...registerResult, commandType: "registerGoodsReceipt" };
      }
      const mutationResult = storedMutationSuccess(stored);
      const mutationType = mutationCommandTypeOf(stored?.type);
      if (mutationResult && mutationType) {
        logG1("grin_g1_replayed", { replayed: true, attempt });
        return { ...mutationResult, commandType: mutationType };
      }
      return deny("not_found", "command not found");
    });
  }

  async amendFields(caller: TrustedCaller, envelope: unknown): Promise<G1MutationResult> {
    return this.mutate(caller, envelope, "amendFields");
  }

  async recordQc(caller: TrustedCaller, envelope: unknown): Promise<G1MutationResult> {
    return this.mutate(caller, envelope, "recordQc");
  }

  async dispatchReturn(caller: TrustedCaller, envelope: unknown): Promise<G1MutationResult> {
    return this.mutate(caller, envelope, "dispatchReturn");
  }

  async correctReturnDispatch(caller: TrustedCaller, envelope: unknown): Promise<G1MutationResult> {
    return this.mutate(caller, envelope, "correctReturnDispatch");
  }

  async voidWithReason(caller: TrustedCaller, envelope: unknown): Promise<G1MutationResult> {
    return this.mutate(caller, envelope, "voidWithReason");
  }

  async recordEwbObservation(caller: TrustedCaller, envelope: unknown): Promise<G1MutationResult> {
    return this.mutate(caller, envelope, "recordEwbObservation");
  }

  async linkVerifiedEvidence(caller: TrustedCaller, envelope: unknown): Promise<G1MutationResult> {
    return this.mutate(caller, envelope, "linkVerifiedEvidence");
  }

  /**
   * Authorized retrieve of confirmed original, events, effective, eventVersion, headHash.
   * Same identity/ledger/admission gate as mutations. Foreign callers forbidden.
   * Missing authorized receipt not_found. Does not invent versions.
   */
  async readReceipt(caller: TrustedCaller, input: unknown): Promise<GrinReceiptReadResult> {
    if (!caller.uid) return deny("unauthenticated", GENERIC_DENY);
    const uid = caller.uid;

    return this.runReadAttempts(async (tx, attempt) => {
      const scope = await this.readAdmissionScope(tx, uid, input);
      const gate = this.gate(
        scope.admissionSnap.data(),
        scope.userSnap.exists,
        scope.userSnap.data(),
        { peeked: scope.ledgerPeeked, exists: scope.ledgerSnap.exists, data: scope.ledgerSnap.data() },
        uid
      );
      if (!gate.ok) return gate;
      if (gate.policy.newCommands !== "allow") return deny("policy_denied", GENERIC_DENY);

      const prepared = this.prepareRead(input);
      if (!prepared.ok) return prepared;

      const receiptRef = this.db.doc(receiptPath(uid, prepared.ledgerId, prepared.receiptId));
      const receiptSnap = await tx.get(receiptRef);
      const eventSnaps = await tx.list(eventsCollectionPath(uid, prepared.ledgerId, prepared.receiptId));
      await this.hooks.afterReads?.(attempt);

      if (!receiptSnap.exists) return deny("not_found", "receipt not found");
      const receipt = hydrateReceipt(receiptSnap.data());
      if (!receipt) return deny("not_found", "receipt not found");
      if (receipt.original.ownerUid !== uid || receipt.original.ledgerId !== prepared.ledgerId) {
        return deny("forbidden", GENERIC_DENY);
      }

      const events: GrinEvent[] = [];
      for (const snap of eventSnaps) {
        const event = hydrateStoredEvent(snap.data());
        if (!event) return deny("integrity", GENERIC_DENY);
        events.push(event);
      }
      const confirmed = assembleConfirmed(receipt, events, prepared.receiptId);
      if (!confirmed) return deny("integrity", GENERIC_DENY);
      return { ok: true, confirmed };
    });
  }

  private gate(
    admission: Record<string, unknown> | undefined,
    userExists: boolean,
    user: Record<string, unknown> | undefined,
    ledger: { peeked: boolean; exists: boolean; data: Record<string, unknown> | undefined },
    uid: string
  ): { ok: true; policy: AdmissionPolicy } | G1Deny {
    if (!userExists) return deny("forbidden", GENERIC_DENY);
    if ((user?.status ?? "active") !== "active") return deny("forbidden", GENERIC_DENY);
    if (ledger.peeked) {
      if (!ledger.exists) return deny("forbidden", GENERIC_DENY);
      if (ledger.data?.ownerUid !== uid) return deny("forbidden", GENERIC_DENY);
      if (ledger.data?.status !== "active") return deny("forbidden", GENERIC_DENY);
    }
    const policy = parsePolicy(admission);
    if (!policy) return deny("policy_denied", GENERIC_DENY);
    return { ok: true, policy };
  }

  private async readAdmissionScope(
    tx: G1Transaction,
    uid: string,
    input: unknown
  ): Promise<{
    userSnap: G1DocSnap;
    ledgerSnap: G1DocSnap;
    admissionSnap: G1DocSnap;
    ledgerPeeked: boolean;
  }> {
    const userSnap = await tx.get(this.db.doc(userPath(uid)));
    const ledgerId = peekLedgerId(input);
    const ledgerSnap = ledgerId ? await tx.get(this.db.doc(ledgerPath(uid, ledgerId))) : ABSENT_SNAP;
    const admissionSnap = await tx.get(this.db.doc(admissionPath(uid)));
    return { userSnap, ledgerSnap, admissionSnap, ledgerPeeked: ledgerId != null };
  }

  private prepareRegister(
    envelope: unknown,
    uid: string
  ): { ok: true; frozen: FrozenRegister } | G1Deny {
    const pre = this.prevalidate(envelope);
    if (pre) return pre;
    const normalized = normalizeJsonCopy(envelope) as {
      commandId: string;
      type: string;
      ledgerId: string;
      body: unknown;
      digest?: string;
    };
    const digest = freezeDigest({
      commandId: normalized.commandId,
      type: "registerGoodsReceipt",
      ownerUid: uid,
      ledgerId: normalized.ledgerId,
      body: normalized.body,
    });
    if (typeof normalized.digest === "string" && normalized.digest !== digest) {
      return deny("digest_conflict", "same commandId with a different body");
    }
    const frozen: FrozenRegister = {
      commandId: normalized.commandId,
      type: "registerGoodsReceipt",
      ownerUid: uid,
      ledgerId: normalized.ledgerId,
      body: normalized.body as RegisterGoodsReceiptBody,
      digest,
    };
    const envelopeErr = commandEnvelopeError(frozen, "registerGoodsReceipt");
    if (envelopeErr) return deny("invalid", envelopeErr);
    const bodyErr = registerBodyError(frozen.body);
    if (bodyErr) return deny("invalid", bodyErr);
    return { ok: true, frozen };
  }

  private prepareReconcile(
    input: unknown
  ): { ok: true; ledgerId: string; commandId: string } | G1Deny {
    if (!isPlainObject(input)) return deny("invalid", "reconcile request is required");
    const shape = inputShapeError(input, "reconcile request");
    if (shape) return deny("invalid", shape);
    const extra = extraReconcileKeyError(input);
    if (extra) return deny("invalid", extra);
    const normalized = normalizeJsonCopy(input) as { ledgerId: unknown; commandId: unknown };
    const ledgerErr = documentIdError("ledgerId", normalized.ledgerId);
    if (ledgerErr) return deny("invalid", ledgerErr);
    const cmdErr = commandIdError(normalized.commandId);
    if (cmdErr) return deny("invalid", cmdErr);
    return { ok: true, ledgerId: normalized.ledgerId as string, commandId: normalized.commandId as string };
  }

  private prepareRead(
    input: unknown
  ): { ok: true; ledgerId: string; receiptId: string } | G1Deny {
    if (!isPlainObject(input)) return deny("invalid", "read request is required");
    const shape = inputShapeError(input, "read request");
    if (shape) return deny("invalid", shape);
    const extra = extraReadKeyError(input);
    if (extra) return deny("invalid", extra);
    const normalized = normalizeJsonCopy(input) as { ledgerId: unknown; receiptId: unknown };
    const ledgerErr = documentIdError("ledgerId", normalized.ledgerId);
    if (ledgerErr) return deny("invalid", ledgerErr);
    const receiptErr = documentIdError("receiptId", normalized.receiptId);
    if (receiptErr) return deny("invalid", receiptErr);
    return { ok: true, ledgerId: normalized.ledgerId as string, receiptId: normalized.receiptId as string };
  }

  private prepareMutation(
    envelope: unknown,
    expectedType: MutationCommandType,
    uid: string
  ): { ok: true; frozen: FrozenMutation } | G1Deny {
    const pre = this.prevalidateMutation(envelope, expectedType);
    if (pre) return pre;
    const normalized = normalizeJsonCopy(envelope) as {
      commandId: string;
      type: string;
      ledgerId: string;
      body: unknown;
      digest?: string;
    };
    const digest = freezeDigest({
      commandId: normalized.commandId,
      type: expectedType,
      ownerUid: uid,
      ledgerId: normalized.ledgerId,
      body: normalized.body,
    });
    if (typeof normalized.digest === "string" && normalized.digest !== digest) {
      return deny("digest_conflict", "same commandId with a different body");
    }
    const frozen: FrozenMutation = {
      commandId: normalized.commandId,
      type: expectedType,
      ownerUid: uid,
      ledgerId: normalized.ledgerId,
      body: normalized.body,
      digest,
    };
    const envelopeErr = commandEnvelopeError(frozen, expectedType);
    if (envelopeErr) return deny("invalid", envelopeErr);
    const bodyErr = this.mutationBodyError(expectedType, frozen.body);
    if (bodyErr) return deny("invalid", bodyErr);
    return { ok: true, frozen };
  }

  private prevalidate(envelope: unknown): G1Deny | null {
    if (!isPlainObject(envelope)) return deny("invalid", "command envelope is required");
    const shape = inputShapeError(envelope, "command envelope");
    if (shape) return deny("invalid", shape);
    const extra = extraEnvelopeKeyError(envelope);
    if (extra) return deny("invalid", extra);
    const bytes = envelopeByteError(envelope);
    if (bytes) return deny("invalid", bytes);
    const cmdErr = commandIdError(envelope.commandId);
    if (cmdErr) return deny("invalid", cmdErr);
    const ledgerErr = documentIdError("ledgerId", envelope.ledgerId);
    if (ledgerErr) return deny("invalid", ledgerErr);
    if (envelope.type !== "registerGoodsReceipt") {
      return deny("invalid", "command type must be registerGoodsReceipt");
    }
    const receiptErr = documentIdError("receiptId", (envelope.body as { receiptId?: unknown })?.receiptId);
    if (receiptErr) return deny("invalid", receiptErr);
    if (isPlainObject(envelope.body) && Array.isArray(envelope.body.lines)) {
      for (let i = 0; i < envelope.body.lines.length; i++) {
        const line = envelope.body.lines[i];
        const lineId = isPlainObject(line) ? line.lineId : undefined;
        const idErr = lineIdError(lineId, i);
        if (idErr) return deny("invalid", idErr);
      }
    }
    const sparse = sparseArrayError(envelope.body, "body");
    if (sparse) return deny("invalid", sparse);
    const server = serverFieldError(envelope.body);
    if (server) return deny("invalid", server);
    const lines = lineCountError(envelope.body);
    if (lines) return deny("invalid", lines);
    const text = textLimitError(envelope.body);
    if (text) return deny("invalid", text);
    return null;
  }

  private buildIssued(
    frozen: FrozenRegister,
    uid: string,
    serverMs: number,
    fyToken: string,
    serial: number
  ): IssuedBuild | G1Deny {
    const serverRegisteredAtUtc = formatUtcIso(serverMs);
    let issuedNumber: string;
    try {
      issuedNumber = formatGrinNumber({ series: frozen.body.series, fyToken, serial });
    } catch {
      return deny("invalid", "issued number could not be formed");
    }
    const body = cloneSnapshot(frozen.body);
    const draft: ImmutableGrin = {
      schemaVersion: GOODS_EVIDENCE_SCHEMA_VERSION,
      receiptId: body.receiptId,
      ownerUid: uid,
      ledgerId: frozen.ledgerId,
      series: body.series,
      serial,
      issuedNumber,
      fyToken,
      buyer: body.buyer,
      supplier: body.supplier,
      commercial: body.commercial,
      ewb: body.ewb,
      transport: body.transport,
      lines: body.lines,
      custody: body.custody,
      receivingEmployeeAttributed: body.receivingEmployeeAttributed,
      qualityCheckedByAttributed: body.qualityCheckedByAttributed,
      remarks: body.remarks,
      acknowledgement: body.acknowledgement,
      warehouse: body.warehouse,
      locationBin: body.locationBin,
      captureProvenance: body.captureProvenance,
      capturedAtClientUtc: body.capturedAtClientUtc,
      reportedArrivalAt: body.reportedArrivalAt,
      reportedArrivalTimeZone: body.reportedArrivalTimeZone,
      serverRegisteredAtUtc,
      originalSnapshotHash: null,
    };
    const envelopeErr = effectiveRecordError(draft);
    if (envelopeErr) return deny("invalid", envelopeErr);
    const originalSnapshotHash = hashOriginalSnapshot(draft);
    const original = cloneSnapshot({ ...draft, originalSnapshotHash });
    const eventId = this.clock.uuid();
    const typedChanges = { issuedNumber, serial, fyToken, originalSnapshotHash };
    const eventHash = hashEventEnvelope({
      eventId,
      receiptId: original.receiptId,
      streamSequence: 1,
      type: "receipt_registered",
      actorUid: uid,
      serverAcceptedAtUtc: serverRegisteredAtUtc,
      clientObservedAtUtc: body.clientObservedAtUtc,
      reason: "issued",
      expectedPreviousVersion: 0,
      typedChanges,
      previousHash: null,
    });
    const event: GrinEvent = {
      schemaVersion: GOODS_EVIDENCE_SCHEMA_VERSION,
      eventId,
      receiptId: original.receiptId,
      streamSequence: 1,
      type: "receipt_registered",
      actorUid: uid,
      serverAcceptedAtUtc: serverRegisteredAtUtc,
      clientObservedAtUtc: body.clientObservedAtUtc,
      reason: "issued",
      expectedPreviousVersion: 0,
      typedChanges: cloneSnapshot(typedChanges),
      previousHash: null,
      eventHash,
      firestoreCommitTime: null,
    };
    const lineLedgers = Object.create(null) as Record<string, LineQuantityLedgers>;
    for (const line of original.lines) {
      const ledgers = emptyLedgers(line.unit);
      ledgers.physicalReceived = { ...line.physicallyReceived };
      if (original.custody === "refused_at_gate") {
        ledgers.acceptedForStock = emptyLedgers(line.unit).acceptedForStock;
      }
      lineLedgers[line.lineId] = cloneSnapshot(ledgers);
      if (!Object.prototype.hasOwnProperty.call(lineLedgers, line.lineId)) {
        return deny("invalid", "line identity could not be projected");
      }
    }
    const view: GrinView = {
      schemaVersion: GOODS_EVIDENCE_SCHEMA_VERSION,
      receiptId: original.receiptId,
      eventVersion: 1,
      headHash: event.eventHash,
      issuedNumber,
      custody: original.custody,
      qcStatus: null,
      voided: false,
      warnings: [],
    };
    view.custody = derivePhysicalCustody({
      originalDisposition: original.custody,
      qcStatus: view.qcStatus,
      lineLedgers: Object.values(lineLedgers),
    });
    return {
      original,
      event,
      view,
      lineLedgers,
      result: {
        ok: true,
        replayed: false,
        receiptId: original.receiptId,
        issuedNumber,
        serial,
        serverRegisteredAtUtc,
        eventVersion: 1,
        headHash: event.eventHash,
      },
    };
  }

  private prevalidateMutation(envelope: unknown, expectedType: MutationCommandType): G1Deny | null {
    if (!isPlainObject(envelope)) return deny("invalid", "command envelope is required");
    const shape = inputShapeError(envelope, "command envelope");
    if (shape) return deny("invalid", shape);
    const extra = extraEnvelopeKeyError(envelope);
    if (extra) return deny("invalid", extra);
    const bytes = envelopeByteError(envelope);
    if (bytes) return deny("invalid", bytes);
    const cmdErr = commandIdError(envelope.commandId);
    if (cmdErr) return deny("invalid", cmdErr);
    const ledgerErr = documentIdError("ledgerId", envelope.ledgerId);
    if (ledgerErr) return deny("invalid", ledgerErr);
    if (envelope.type !== expectedType) {
      return deny("invalid", `command type must be ${expectedType}`);
    }
    if (!(MUTATION_COMMAND_TYPES as readonly string[]).includes(expectedType)) {
      return deny("invalid", `command type must be ${expectedType}`);
    }
    const receiptErr = documentIdError("receiptId", (envelope.body as { receiptId?: unknown })?.receiptId);
    if (receiptErr) return deny("invalid", receiptErr);
    if (expectedType === "dispatchReturn" || expectedType === "correctReturnDispatch") {
      const lineId = (envelope.body as { lineId?: unknown })?.lineId;
      const idErr = lineIdError(lineId);
      if (idErr) return deny("invalid", idErr);
    }
    if (expectedType === "linkVerifiedEvidence") {
      const evidenceId = (envelope.body as { verified?: { evidenceId?: unknown } })?.verified?.evidenceId;
      const evidenceErr = documentIdError("evidenceId", evidenceId);
      if (evidenceErr) return deny("invalid", evidenceErr);
    }
    const sparse = sparseArrayError(envelope.body, "body");
    if (sparse) return deny("invalid", sparse);
    const server = serverFieldError(envelope.body);
    if (server) return deny("invalid", server);
    const text = textLimitError(envelope.body);
    if (text) return deny("invalid", text);
    return null;
  }

  private mutationBodyError(type: MutationCommandType, body: unknown): string | null {
    const reason = isPlainObject(body) ? body.reason : undefined;
    const base = mutationBodyError(body) ?? commandReasonError(reason);
    if (base) return base;
    if (type === "recordEwbObservation") return recordEwbObservationBodyError(body);
    if (type === "linkVerifiedEvidence") return linkVerifiedEvidenceBodyError(body);
    return null;
  }

  private applyMutation(
    type: MutationCommandType,
    receipt: PersistedReceipt,
    body: unknown,
    eventId: string,
    uid: string
  ): ReturnType<typeof applyAmendFields> {
    if (type === "amendFields") return applyAmendFields(receipt, body as AmendFieldsBody);
    if (type === "recordQc") return applyRecordQc(receipt, body as RecordQcBody);
    if (type === "dispatchReturn") return applyDispatchReturn(receipt, body as DispatchReturnBody, eventId);
    if (type === "correctReturnDispatch") {
      return applyCorrectReturnDispatch(receipt, body as CorrectReturnDispatchBody);
    }
    if (type === "voidWithReason") return applyVoidWithReason(receipt, body as VoidWithReasonBody);
    if (type === "recordEwbObservation") {
      return applyRecordEwbObservation(receipt, body as RecordEwbObservationBody);
    }
    const verifiedBody = body as LinkVerifiedEvidenceBody;
    const identity = verifiedEvidenceIdentityError(verifiedBody.verified, {
      ownerUid: uid,
      ledgerId: receipt.original.ledgerId,
      receiptId: receipt.original.receiptId,
    });
    if (identity) return { ok: false, detail: identity };
    return applyLinkVerifiedEvidence(receipt, verifiedBody);
  }

  private async mutate(
    caller: TrustedCaller,
    envelope: unknown,
    expectedType: MutationCommandType
  ): Promise<G1MutationResult> {
    if (!caller.uid) return deny("unauthenticated", GENERIC_DENY);
    const uid = caller.uid;

    return this.runAttempts(async (tx, attempt) => {
      const scope = await this.readAdmissionScope(tx, uid, envelope);
      const gate = this.gate(
        scope.admissionSnap.data(),
        scope.userSnap.exists,
        scope.userSnap.data(),
        { peeked: scope.ledgerPeeked, exists: scope.ledgerSnap.exists, data: scope.ledgerSnap.data() },
        uid
      );
      if (!gate.ok) return gate;
      if (gate.policy.newCommands !== "allow") return deny("policy_denied", GENERIC_DENY);

      const prepared = this.prepareMutation(envelope, expectedType, uid);
      if (!prepared.ok) return prepared;
      const frozen = prepared.frozen;
      const receiptId = (frozen.body as { receiptId: string }).receiptId;
      const expectedVersion = (frozen.body as { expectedVersion: number }).expectedVersion;

      const serverMs = this.clock.nowMs();
      const commandRef = this.db.doc(commandPath(uid, frozen.ledgerId, frozen.commandId));
      const commandSnap = await tx.get(commandRef);
      const receiptRef = this.db.doc(receiptPath(uid, frozen.ledgerId, receiptId));
      const receiptSnap = await tx.get(receiptRef);
      await this.hooks.afterReads?.(attempt);

      if (commandSnap.exists) {
        const stored = commandSnap.data();
        if (stored?.digest !== frozen.digest) {
          return deny("digest_conflict", "same commandId with a different body");
        }
        const result = storedMutationSuccess(stored);
        if (!result || stored?.type !== expectedType) {
          return deny("digest_conflict", "commandId is not this mutation command");
        }
        logG1("grin_g1_replayed", { replayed: true, attempt });
        return result;
      }

      if (!receiptSnap.exists) return deny("not_found", "receipt not found");
      const receipt = hydrateReceipt(receiptSnap.data());
      if (!receipt) return deny("not_found", "receipt not found");
      if (receipt.original.ownerUid !== uid || receipt.original.ledgerId !== frozen.ledgerId) {
        return deny("forbidden", GENERIC_DENY);
      }
      if (receipt.view.voided) return deny("voided", "receipt is void");
      if (receipt.view.eventVersion !== expectedVersion) {
        return deny(
          "version_conflict",
          `intervening amendment at version ${receipt.view.eventVersion}`
        );
      }

      const eventId = this.clock.uuid();
      const applied = this.applyMutation(expectedType, receipt, frozen.body, eventId, uid);
      if (!applied.ok) return deny("invalid", applied.detail);

      const serverAcceptedAtUtc = formatUtcIso(serverMs);
      const streamSequence = receipt.view.eventVersion + 1;
      const eventHash = hashEventEnvelope({
        eventId,
        receiptId,
        streamSequence,
        type: applied.eventType,
        actorUid: uid,
        serverAcceptedAtUtc,
        clientObservedAtUtc: (frozen.body as { clientObservedAtUtc: string }).clientObservedAtUtc,
        reason: (frozen.body as { reason: string }).reason.trim(),
        expectedPreviousVersion: expectedVersion,
        typedChanges: applied.typedChanges,
        previousHash: receipt.view.headHash,
      });
      const event: GrinEvent = {
        schemaVersion: GOODS_EVIDENCE_SCHEMA_VERSION,
        eventId,
        receiptId,
        streamSequence,
        type: applied.eventType,
        actorUid: uid,
        serverAcceptedAtUtc,
        clientObservedAtUtc: (frozen.body as { clientObservedAtUtc: string }).clientObservedAtUtc,
        reason: (frozen.body as { reason: string }).reason.trim(),
        expectedPreviousVersion: expectedVersion,
        typedChanges: cloneSnapshot(applied.typedChanges),
        previousHash: receipt.view.headHash,
        eventHash,
        firestoreCommitTime: null,
      };
      applied.next.view.eventVersion = streamSequence;
      applied.next.view.headHash = eventHash;
      const persisted = persistableReceipt(applied.next);
      persisted.original = cloneSnapshot(receipt.original);
      tx.set(receiptRef, persisted);
      tx.set(this.db.doc(eventPath(uid, frozen.ledgerId, receiptId, eventId)), { ...event });
      const result: G1MutationSuccess = {
        ok: true,
        replayed: false,
        receiptId,
        eventId,
        eventVersion: streamSequence,
        headHash: eventHash,
        serverAcceptedAtUtc,
      };
      tx.set(commandRef, {
        schemaVersion: GOODS_EVIDENCE_SCHEMA_VERSION,
        ownerUid: uid,
        ledgerId: frozen.ledgerId,
        commandId: frozen.commandId,
        type: expectedType,
        digest: frozen.digest,
        receiptId,
        result: { ...result, replayed: false },
      });
      return result;
    });
  }

  private async runAttempts<T extends G1CommandResult>(
    fn: (tx: G1Transaction, attempt: number) => Promise<T>
  ): Promise<T> {
    let last: unknown;
    for (let attempt = 1; attempt <= MAX_TX_ATTEMPTS; attempt++) {
      // Capture locally. The Firestore SDK/emulator may drop the callback return value.
      let outcome: T | undefined;
      try {
        await this.db.runTransaction(
          async (tx) => {
            outcome = await fn(tx, attempt);
          },
          { maxAttempts: 1 }
        );
      } catch (err) {
        last = err;
        if (attempt < MAX_TX_ATTEMPTS && isRetryable(err)) continue;
        throw err;
      }
      if (!outcome) {
        throw new Error("g1_transaction_missing_result");
      }
      if (outcome.ok && outcome.replayed === false) {
        if ("issuedNumber" in outcome) {
          logG1("grin_g1_committed", { replayed: false });
        } else {
          logG1("grin_g1_mutation_committed", { replayed: false });
        }
      }
      return outcome;
    }
    throw last;
  }

  private async runReadAttempts(
    fn: (tx: G1Transaction, attempt: number) => Promise<GrinReceiptReadResult>
  ): Promise<GrinReceiptReadResult> {
    let last: unknown;
    for (let attempt = 1; attempt <= MAX_TX_ATTEMPTS; attempt++) {
      let outcome: GrinReceiptReadResult | undefined;
      try {
        await this.db.runTransaction(
          async (tx) => {
            outcome = await fn(tx, attempt);
          },
          { maxAttempts: 1 }
        );
      } catch (err) {
        last = err;
        if (attempt < MAX_TX_ATTEMPTS && isRetryable(err)) continue;
        throw err;
      }
      if (!outcome) {
        throw new Error("g1_transaction_missing_result");
      }
      return outcome;
    }
    throw last;
  }
}
