/** GENERATED by tools/goods-evidence-emulator/packageFunctionsGoodsEvidence.ts — do not hand-edit. */
/**
 * Durable mutation apply against persisted receipt documents.
 * Trusted adapter path — not InMemoryGoodsLedger.
 */

import type {
  AmendFieldsBody,
  CorrectReturnDispatchBody,
  DispatchReturnBody,
  LinkVerifiedEvidenceBody,
  RecordEwbObservationBody,
  RecordQcBody,
  VoidWithReasonBody,
} from "../command";
import { derivePhysicalCustody } from "../custody";
import {
  appendMovementEvent,
  appendPortalObservation,
  appendQcEvent,
  emptyEwbHistories,
  linkReplacement,
  type EwbHistories,
} from "../ewb";
import {
  applyReturnCorrection,
  applyReturnDispatch,
  compareDecimal,
  IncompatibleUnitsError,
  QuantityBoundError,
  quantityShapeError,
  subtractQuantity,
  type LineQuantityLedgers,
  type Quantity,
} from "../quantities";
import { cloneSnapshot } from "../snapshot";
import type { GrinEvent, GrinView, ImmutableGrin } from "../types";
import {
  amendmentFieldError,
  effectiveRecordError,
  isAmendableGrinField,
  qcStatusError,
} from "../validate";

export type ReturnDispatchProjection = {
  lineId: string;
  unit: string;
  returnQty: Quantity;
  remaining: Quantity;
};

export type LinkedEvidencePointer = {
  evidenceId: string;
  generation: string;
  rawSha256: string;
  storagePath: string;
  byteSize: number;
  mime: string;
  category: string;
  verifiedAtUtc: string;
};

export type PersistedReceipt = {
  original: ImmutableGrin;
  effective: ImmutableGrin;
  view: GrinView;
  lineLedgers: Record<string, LineQuantityLedgers>;
  ewbHistories: EwbHistories;
  returnDispatches: Record<string, ReturnDispatchProjection>;
  linkedEvidence: LinkedEvidencePointer[];
};

export type AppliedMutation = {
  next: PersistedReceipt;
  eventType: GrinEvent["type"];
  typedChanges: Record<string, unknown>;
};

export type ApplyResult = { ok: true } & AppliedMutation | { ok: false; detail: string };

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return value != null && typeof value === "object" && !Array.isArray(value);
}

function asQuantity(value: unknown): Quantity | null {
  if (!value || typeof value !== "object") return null;
  const qty = value as Quantity;
  if (typeof qty.value !== "string" || typeof qty.unit !== "string") return null;
  return qty;
}

function cloneLineLedgers(ledgers: Record<string, LineQuantityLedgers>): Record<string, LineQuantityLedgers> {
  const next = Object.create(null) as Record<string, LineQuantityLedgers>;
  for (const key of Object.keys(ledgers)) {
    next[key] = cloneSnapshot(ledgers[key]!);
  }
  return next;
}

function cloneReturnDispatches(
  value: Record<string, ReturnDispatchProjection>
): Record<string, ReturnDispatchProjection> {
  const next = Object.create(null) as Record<string, ReturnDispatchProjection>;
  for (const key of Object.keys(value)) {
    next[key] = cloneSnapshot(value[key]!);
  }
  return next;
}

export function hydrateReceipt(data: Record<string, unknown> | undefined): PersistedReceipt | null {
  if (!data || !isPlainObject(data.original) || !isPlainObject(data.view) || !isPlainObject(data.lineLedgers)) {
    return null;
  }
  const original = data.original as unknown as ImmutableGrin;
  const effective = isPlainObject(data.effective)
    ? (data.effective as unknown as ImmutableGrin)
    : cloneSnapshot(original);
  const ewbHistories = isPlainObject(data.ewbHistories)
    ? (data.ewbHistories as unknown as EwbHistories)
    : emptyEwbHistories();
  const returnDispatches = isPlainObject(data.returnDispatches)
    ? cloneReturnDispatches(data.returnDispatches as unknown as Record<string, ReturnDispatchProjection>)
    : (Object.create(null) as Record<string, ReturnDispatchProjection>);
  const linkedEvidence = Array.isArray(data.linkedEvidence)
    ? (cloneSnapshot(data.linkedEvidence) as LinkedEvidencePointer[])
    : [];
  return {
    original: cloneSnapshot(original),
    effective: cloneSnapshot(effective),
    view: cloneSnapshot(data.view as unknown as GrinView),
    lineLedgers: cloneLineLedgers(data.lineLedgers as unknown as Record<string, LineQuantityLedgers>),
    ewbHistories: cloneSnapshot(ewbHistories),
    returnDispatches,
    linkedEvidence,
  };
}

export function persistableReceipt(receipt: PersistedReceipt): Record<string, unknown> {
  return {
    original: cloneSnapshot(receipt.original),
    effective: cloneSnapshot(receipt.effective),
    view: cloneSnapshot(receipt.view),
    lineLedgers: cloneLineLedgers(receipt.lineLedgers),
    ewbHistories: cloneSnapshot(receipt.ewbHistories),
    returnDispatches: cloneReturnDispatches(receipt.returnDispatches),
    linkedEvidence: cloneSnapshot(receipt.linkedEvidence),
  };
}

function syncCustody(next: PersistedReceipt): void {
  next.view.custody = derivePhysicalCustody({
    originalDisposition: next.original.custody,
    qcStatus: next.view.qcStatus,
    lineLedgers: Object.values(next.lineLedgers),
  });
}

export function applyAmendFields(receipt: PersistedReceipt, body: AmendFieldsBody): ApplyResult {
  const keys = Object.keys(body.changes ?? {});
  if (keys.length === 0) return { ok: false, detail: "amendment changes are required" };
  const next = hydrateReceipt(persistableReceipt(receipt));
  if (!next) return { ok: false, detail: "receipt could not be projected" };
  const oldValues: Record<string, unknown> = {};
  for (const key of keys) {
    if (!isAmendableGrinField(key)) return { ok: false, detail: `field ${key} is not amendable` };
    const fieldErr = amendmentFieldError(key, body.changes[key]);
    if (fieldErr) return { ok: false, detail: fieldErr };
    oldValues[key] = cloneSnapshot((next.effective as unknown as Record<string, unknown>)[key] ?? null);
    (next.effective as unknown as Record<string, unknown>)[key] = cloneSnapshot(body.changes[key]);
  }
  const envelopeErr = effectiveRecordError(next.effective);
  if (envelopeErr) return { ok: false, detail: envelopeErr };
  void body.claimedOldValues;
  return {
    ok: true,
    next,
    eventType: "field_amended",
    typedChanges: { oldValues, newValues: cloneSnapshot(body.changes) },
  };
}

export function applyRecordQc(receipt: PersistedReceipt, body: RecordQcBody): ApplyResult {
  const qcErr = qcStatusError(body.qcStatus);
  if (qcErr) return { ok: false, detail: qcErr };
  const next = hydrateReceipt(persistableReceipt(receipt));
  if (!next) return { ok: false, detail: "receipt could not be projected" };
  const previousQc = next.view.qcStatus;
  next.view.qcStatus = body.qcStatus;
  syncCustody(next);
  return {
    ok: true,
    next,
    eventType: previousQc == null ? "qc_decision" : "qc_reclassified",
    typedChanges: { oldQc: previousQc, newQc: body.qcStatus },
  };
}

export function applyDispatchReturn(
  receipt: PersistedReceipt,
  body: DispatchReturnBody,
  eventId: string
): ApplyResult {
  const next = hydrateReceipt(persistableReceipt(receipt));
  if (!next) return { ok: false, detail: "receipt could not be projected" };
  const ledger = next.lineLedgers[body.lineId];
  if (!ledger) return { ok: false, detail: "unknown line" };
  const qtyErr = quantityShapeError(body.returnQty, {
    label: "returnQty",
    requiredUnit: ledger.physicalReceived.unit,
  });
  if (qtyErr) return { ok: false, detail: qtyErr };
  try {
    const physicalBefore = ledger.physicalReceived.value;
    const updated = applyReturnDispatch(ledger, body.returnQty);
    next.lineLedgers[body.lineId] = updated;
    next.returnDispatches[eventId] = {
      lineId: body.lineId,
      unit: body.returnQty.unit,
      returnQty: cloneSnapshot(body.returnQty),
      remaining: cloneSnapshot(body.returnQty),
    };
    syncCustody(next);
    return {
      ok: true,
      next,
      eventType: "return_dispatched",
      typedChanges: {
        lineId: body.lineId,
        unit: body.returnQty.unit,
        returnQty: cloneSnapshot(body.returnQty),
        physicalReceivedUnchanged: updated.physicalReceived.value === physicalBefore,
      },
    };
  } catch (err) {
    if (err instanceof QuantityBoundError || err instanceof IncompatibleUnitsError) {
      return { ok: false, detail: err.message };
    }
    throw err;
  }
}

export function applyCorrectReturnDispatch(
  receipt: PersistedReceipt,
  body: CorrectReturnDispatchBody
): ApplyResult {
  if (!body.linkedEventId?.trim()) {
    return { ok: false, detail: "linkedEventId is required for a return correction" };
  }
  const next = hydrateReceipt(persistableReceipt(receipt));
  if (!next) return { ok: false, detail: "receipt could not be projected" };
  const linked = next.returnDispatches[body.linkedEventId];
  if (!linked) return { ok: false, detail: "linked return_dispatched event not found" };
  if (body.lineId !== linked.lineId) {
    return { ok: false, detail: "correction line must match the linked dispatch" };
  }
  if (body.correctionQty.unit !== linked.unit) {
    return { ok: false, detail: "correction unit must match the linked dispatch" };
  }
  const remaining = asQuantity(linked.remaining);
  if (!remaining) return { ok: false, detail: "linked dispatch is missing remaining quantity" };
  if (compareDecimal(body.correctionQty.value, remaining.value) > 0) {
    return { ok: false, detail: "correction exceeds remaining linked dispatch quantity" };
  }
  const ledger = next.lineLedgers[linked.lineId];
  if (!ledger) return { ok: false, detail: "unknown line" };
  const qtyErr = quantityShapeError(body.correctionQty, {
    label: "correctionQty",
    requiredUnit: linked.unit,
  });
  if (qtyErr) return { ok: false, detail: qtyErr };
  try {
    const updated = applyReturnCorrection(ledger, body.correctionQty);
    next.lineLedgers[linked.lineId] = updated;
    next.returnDispatches[body.linkedEventId] = {
      ...linked,
      remaining: subtractQuantity(remaining, body.correctionQty),
    };
    syncCustody(next);
    return {
      ok: true,
      next,
      eventType: "return_received",
      typedChanges: {
        lineId: body.lineId,
        linkedEventId: body.linkedEventId,
        correctionQty: cloneSnapshot(body.correctionQty),
        physicalReceivedUnchanged: true,
      },
    };
  } catch (err) {
    if (err instanceof QuantityBoundError || err instanceof IncompatibleUnitsError) {
      return { ok: false, detail: err.message };
    }
    throw err;
  }
}

export function applyVoidWithReason(receipt: PersistedReceipt, body: VoidWithReasonBody): ApplyResult {
  const next = hydrateReceipt(persistableReceipt(receipt));
  if (!next) return { ok: false, detail: "receipt could not be projected" };
  const issuedNumber = next.original.issuedNumber;
  next.view.voided = true;
  return {
    ok: true,
    next,
    eventType: "void_with_reason",
    typedChanges: { issuedNumberPreserved: issuedNumber, linkedReceiptId: body.linkedReceiptId },
  };
}

export function applyRecordEwbObservation(
  receipt: PersistedReceipt,
  body: RecordEwbObservationBody
): ApplyResult {
  const next = hydrateReceipt(persistableReceipt(receipt));
  if (!next) return { ok: false, detail: "receipt could not be projected" };
  try {
    if (body.channel === "portal") {
      const appended = appendPortalObservation(next.ewbHistories, body.observation);
      if (!appended.ok) return { ok: false, detail: appended.detail };
      next.ewbHistories = appended.histories;
      return {
        ok: true,
        next,
        eventType: "ewb_observation_recorded",
        typedChanges: {
          channel: "portal",
          admission: appended.admission,
          incompleteReasons: appended.incompleteReasons ?? null,
          latestStatus:
            appended.histories.portal[appended.histories.portal.length - 1]?.status ?? null,
        },
      };
    }
    if (body.channel === "movement") {
      next.ewbHistories = appendMovementEvent(next.ewbHistories, body.observation);
      return {
        ok: true,
        next,
        eventType: "ewb_observation_recorded",
        typedChanges: { channel: "movement", observation: cloneSnapshot(body.observation) },
      };
    }
    if (body.channel === "qc") {
      next.ewbHistories = appendQcEvent(next.ewbHistories, body.observation);
      return {
        ok: true,
        next,
        eventType: "ewb_observation_recorded",
        typedChanges: { channel: "qc", observation: cloneSnapshot(body.observation) },
      };
    }
    next.ewbHistories = linkReplacement(next.ewbHistories, body.observation);
    return {
      ok: true,
      next,
      eventType: "ewb_observation_recorded",
      typedChanges: { channel: "replacement", observation: cloneSnapshot(body.observation) },
    };
  } catch (err) {
    if (err instanceof Error) return { ok: false, detail: err.message };
    throw err;
  }
}

export function applyLinkVerifiedEvidence(
  receipt: PersistedReceipt,
  body: LinkVerifiedEvidenceBody
): ApplyResult {
  const next = hydrateReceipt(persistableReceipt(receipt));
  if (!next) return { ok: false, detail: "receipt could not be projected" };
  const verified = body.verified;
  if (next.linkedEvidence.some((item) => item.evidenceId === verified.evidenceId)) {
    return { ok: false, detail: "evidence already linked" };
  }
  const pointer: LinkedEvidencePointer = {
    evidenceId: verified.evidenceId,
    generation: verified.generation,
    rawSha256: verified.rawSha256,
    storagePath: verified.storagePath,
    byteSize: verified.byteSize,
    mime: verified.mime,
    category: verified.category,
    verifiedAtUtc: verified.verifiedAtUtc,
  };
  next.linkedEvidence.push(cloneSnapshot(pointer));
  return {
    ok: true,
    next,
    eventType: "evidence_verified",
    typedChanges: { ...cloneSnapshot(pointer), linkOnly: true, bytesNotRehashed: true },
  };
}
