/** GENERATED by tools/goods-evidence-emulator/packageFunctionsGoodsEvidence.ts — do not hand-edit. */
/**
 * Server-side monthly issuance quota for GRIN register (Admin transaction).
 *
 * Mirrors src/billing/optionC/usageTransition.ts + monthlyRecordCap without
 * AppError or @/ imports (packaging-safe). lastRecordCollection value is
 * `goodsEvidenceReceipts` — a parallel label, not a client-writable top-level
 * collection. Mutations, retry, QC, return, evidence link, and reconcile do
 * not call this module.
 */

export const GRIN_USAGE_COLLECTION = "goodsEvidenceReceipts" as const;

export const UNLIMITED_MONTHLY_RECORD_CAP = -1;
export const FREE_MONTHLY_RECORD_CAP = 25;
export const STARTER_MONTHLY_RECORD_CAP = 100;
export const IST_UTC_OFFSET_MS = 19_800_000;

export type GrinUsageSnapshot = {
  monthKey: string;
  recordsThisMonth: number;
  lastRecordCollection: string;
  lastRecordId: string;
};

export type GrinUsageWrite = {
  monthKey: string;
  recordsThisMonth: number;
  lastRecordCollection: typeof GRIN_USAGE_COLLECTION;
  lastRecordId: string;
  updatedAt: number;
};

export type GrinIssuanceQuotaDecision =
  | { kind: "enforcement_off" }
  | { kind: "write"; doc: GrinUsageWrite }
  | {
      kind: "quota_exhausted";
      recordsThisMonth: number;
      cap: number;
      monthKey: string;
    }
  | { kind: "quota_state_invalid"; reason: string };

export function istMonthKeyForMillis(utcMillis: number): string {
  const shifted = new Date(utcMillis + IST_UTC_OFFSET_MS);
  const year = shifted.getUTCFullYear();
  const month = shifted.getUTCMonth() + 1;
  return `${year}-${month < 10 ? `0${month}` : month}`;
}

export function isIstMonthKeyShape(value: unknown): value is string {
  return typeof value === "string" && value.length === 7 && value.charAt(4) === "-";
}

export function monthlyRecordCapFromStatusData(statusData: Record<string, unknown>): number {
  const entitled = statusData.entitlementActive === true;
  const plan = entitled ? statusData.plan : "free";
  if (plan === "starter") return STARTER_MONTHLY_RECORD_CAP;
  if (plan === "professional" || plan === "business") return UNLIMITED_MONTHLY_RECORD_CAP;
  return FREE_MONTHLY_RECORD_CAP;
}

export function quotaEnforcementEnabledFromStatusData(
  statusData: Record<string, unknown> | undefined
): boolean {
  return statusData?.quotaEnforcementEnabled === true;
}

/**
 * Missing → null. Malformed → quota_state_invalid (never first-create).
 * lastRecordCollection is any non-empty string so historical letterheadDocs
 * and goodsEvidenceReceipts both remain readable.
 */
export function readGrinUsageSnapshot(
  raw: Record<string, unknown> | undefined
): GrinUsageSnapshot | null | { malformed: true } {
  if (raw == null) return null;
  const monthKey = raw.monthKey;
  const recordsThisMonth = raw.recordsThisMonth;
  const lastRecordCollection = raw.lastRecordCollection;
  const lastRecordId = raw.lastRecordId;
  const countIsInt =
    typeof recordsThisMonth === "number" &&
    Number.isInteger(recordsThisMonth) &&
    recordsThisMonth >= 1;
  const collectionOk = typeof lastRecordCollection === "string" && lastRecordCollection.length > 0;
  const idOk = typeof lastRecordId === "string" && lastRecordId.length > 0;
  if (!isIstMonthKeyShape(monthKey) || !countIsInt || !collectionOk || !idOk) {
    return { malformed: true };
  }
  return {
    monthKey,
    recordsThisMonth,
    lastRecordCollection,
    lastRecordId,
  };
}

export function nextGrinUsageWrite(params: {
  existing: GrinUsageSnapshot | null;
  monthKey: string;
  cap: number;
  recordId: string;
  updatedAt: number;
}): GrinIssuanceQuotaDecision {
  const { existing, monthKey, cap, recordId, updatedAt } = params;
  let recordsThisMonth: number;
  if (existing == null) {
    recordsThisMonth = 1;
  } else if (existing.monthKey === monthKey) {
    recordsThisMonth = existing.recordsThisMonth + 1;
  } else {
    recordsThisMonth = 1;
  }
  if (cap !== UNLIMITED_MONTHLY_RECORD_CAP && recordsThisMonth > cap) {
    return {
      kind: "quota_exhausted",
      recordsThisMonth: existing?.monthKey === monthKey ? existing.recordsThisMonth : 0,
      cap,
      monthKey,
    };
  }
  return {
    kind: "write",
    doc: {
      monthKey,
      recordsThisMonth,
      lastRecordCollection: GRIN_USAGE_COLLECTION,
      lastRecordId: recordId,
      updatedAt,
    },
  };
}

/**
 * Status missing → enforcement off. Failed status *read* is the caller's
 * throw (do not pass a fake empty object). quotaEnforcementEnabled false → off.
 */
export function decideGrinIssuanceQuota(params: {
  statusExists: boolean;
  statusData: Record<string, unknown> | undefined;
  usageRaw: Record<string, unknown> | undefined;
  recordId: string;
  nowMs: number;
}): GrinIssuanceQuotaDecision {
  if (!params.statusExists) return { kind: "enforcement_off" };
  if (!quotaEnforcementEnabledFromStatusData(params.statusData)) {
    return { kind: "enforcement_off" };
  }
  const cap = monthlyRecordCapFromStatusData(params.statusData ?? {});
  const usage = readGrinUsageSnapshot(params.usageRaw);
  if (usage && "malformed" in usage) {
    return { kind: "quota_state_invalid", reason: "malformed_usage" };
  }
  return nextGrinUsageWrite({
    existing: usage,
    monthKey: istMonthKeyForMillis(params.nowMs),
    cap,
    recordId: params.recordId,
    updatedAt: params.nowMs,
  });
}
