/** GENERATED by tools/goods-evidence-emulator/packageFunctionsGoodsEvidence.ts — do not hand-edit. */
/**
 * Retry only Firestore transaction contention.
 * gRPC ABORTED is 10. gRPC UNAUTHENTICATED is 16 and must not be retried.
 * Message text is not authority.
 */

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return value != null && typeof value === "object" && !Array.isArray(value);
}

export function isRetryable(err: unknown): boolean {
  if (!isPlainObject(err)) return false;
  const code = err.code;
  return code === 10 || code === "ABORTED" || code === "aborted";
}
