/**
 * Statutory information registry — points 1–32 only.
 * Update due rules when Government notifications change filing dates.
 */

import type { StatutoryInfoTemplate } from "@/domain/statutoryInfo";

export const STATUTORY_INFO_REGISTRY: StatutoryInfoTemplate[] = [
  // —— GST (1–11) ——
  {
    id: "gst_gstr1_monthly",
    category: "GST",
    titleKey: "statutory.templates.gst_gstr1_monthly.title",
    applicabilityKey: "statutory.templates.gst_gstr1_monthly.applicability",
    bodyKey: "statutory.templates.gst_gstr1_monthly.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "monthly_day_next_month", day: 11 },
    penaltyNoteKeys: ["statutory.notes.gst_late_fee"],
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 10,
    promptEnabled: true,
  },
  {
    id: "gst_gstr1_quarterly",
    category: "GST",
    titleKey: "statutory.templates.gst_gstr1_quarterly.title",
    applicabilityKey: "statutory.templates.gst_gstr1_quarterly.applicability",
    bodyKey: "statutory.templates.gst_gstr1_quarterly.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "quarterly_day_after_quarter", day: 13, quarterEnds: [3, 6, 9, 12] },
    penaltyNoteKeys: ["statutory.notes.gst_late_fee"],
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 11,
    promptEnabled: true,
  },
  {
    id: "gst_gstr3b_monthly",
    category: "GST",
    titleKey: "statutory.templates.gst_gstr3b_monthly.title",
    applicabilityKey: "statutory.templates.gst_gstr3b_monthly.applicability",
    bodyKey: "statutory.templates.gst_gstr3b_monthly.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "monthly_day_next_month", day: 20 },
    penaltyNoteKeys: ["statutory.notes.gst_interest", "statutory.notes.gst_late_fee"],
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 12,
    promptEnabled: true,
  },
  {
    id: "gst_gstr3b_qrmp",
    category: "GST",
    titleKey: "statutory.templates.gst_gstr3b_qrmp.title",
    applicabilityKey: "statutory.templates.gst_gstr3b_qrmp.applicability",
    bodyKey: "statutory.templates.gst_gstr3b_qrmp.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "quarterly_day_after_quarter", day: 22, quarterEnds: [3, 6, 9, 12] },
    penaltyNoteKeys: ["statutory.notes.gst_interest", "statutory.notes.gst_late_fee"],
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 13,
    promptEnabled: true,
  },
  {
    id: "gst_qrmp_pmt06",
    category: "GST",
    titleKey: "statutory.templates.gst_qrmp_pmt06.title",
    applicabilityKey: "statutory.templates.gst_qrmp_pmt06.applicability",
    bodyKey: "statutory.templates.gst_qrmp_pmt06.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "qrmp_pmt06_monthly", day: 25 },
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 14,
    promptEnabled: true,
  },
  {
    id: "gst_cmp08",
    category: "GST",
    titleKey: "statutory.templates.gst_cmp08.title",
    applicabilityKey: "statutory.templates.gst_cmp08.applicability",
    bodyKey: "statutory.templates.gst_cmp08.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "quarterly_day_after_quarter", day: 18, quarterEnds: [3, 6, 9, 12] },
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 15,
    promptEnabled: true,
  },
  {
    id: "gst_gstr4_annual",
    category: "GST",
    titleKey: "statutory.templates.gst_gstr4_annual.title",
    applicabilityKey: "statutory.templates.gst_gstr4_annual.applicability",
    bodyKey: "statutory.templates.gst_gstr4_annual.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "annual_after_fy", month: 4, day: 30 },
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 16,
    promptEnabled: true,
  },
  {
    id: "gst_gstr9_annual",
    category: "GST",
    titleKey: "statutory.templates.gst_gstr9_annual.title",
    applicabilityKey: "statutory.templates.gst_gstr9_annual.applicability",
    bodyKey: "statutory.templates.gst_gstr9_annual.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "annual_after_fy", month: 12, day: 31 },
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 17,
    promptEnabled: true,
  },
  {
    id: "gst_gstr9c_annual",
    category: "GST",
    titleKey: "statutory.templates.gst_gstr9c_annual.title",
    applicabilityKey: "statutory.templates.gst_gstr9c_annual.applicability",
    bodyKey: "statutory.templates.gst_gstr9c_annual.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "annual_after_fy", month: 12, day: 31 },
    sourceNoteKey: "statutory.source.gst_portal",
    enabled: true,
    priority: 18,
    promptEnabled: true,
  },
  {
    id: "gst_note_interest",
    category: "GST",
    titleKey: "statutory.templates.gst_note_interest.title",
    applicabilityKey: "statutory.templates.gst_note_interest.applicability",
    bodyKey: "statutory.templates.gst_note_interest.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "reference_only" },
    enabled: true,
    priority: 90,
    promptEnabled: false,
    attachedToTemplateId: "gst_gstr3b_monthly",
  },
  {
    id: "gst_note_late_fee",
    category: "GST",
    titleKey: "statutory.templates.gst_note_late_fee.title",
    applicabilityKey: "statutory.templates.gst_note_late_fee.applicability",
    bodyKey: "statutory.templates.gst_note_late_fee.body",
    cautionKey: "statutory.caution.standard",
    dueRule: { kind: "reference_only" },
    enabled: true,
    priority: 91,
    promptEnabled: false,
    attachedToTemplateId: "gst_gstr1_monthly",
  },

  // —— Income Tax (12–20) ——
  {
    id: "it_advance_jun",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_advance_jun.title",
    applicabilityKey: "statutory.templates.it_advance_general.applicability",
    bodyKey: "statutory.templates.it_advance_jun.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "advance_tax_instalment", instalmentMonth: 6, day: 15 },
    penaltyNoteKeys: ["statutory.notes.it_234bc"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 20,
    promptEnabled: true,
  },
  {
    id: "it_advance_sep",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_advance_sep.title",
    applicabilityKey: "statutory.templates.it_advance_general.applicability",
    bodyKey: "statutory.templates.it_advance_sep.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "advance_tax_instalment", instalmentMonth: 9, day: 15 },
    penaltyNoteKeys: ["statutory.notes.it_234bc"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 21,
    promptEnabled: true,
  },
  {
    id: "it_advance_dec",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_advance_dec.title",
    applicabilityKey: "statutory.templates.it_advance_general.applicability",
    bodyKey: "statutory.templates.it_advance_dec.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "advance_tax_instalment", instalmentMonth: 12, day: 15 },
    penaltyNoteKeys: ["statutory.notes.it_234bc"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 22,
    promptEnabled: true,
  },
  {
    id: "it_advance_mar",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_advance_mar.title",
    applicabilityKey: "statutory.templates.it_advance_general.applicability",
    bodyKey: "statutory.templates.it_advance_mar.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "advance_tax_instalment", instalmentMonth: 3, day: 15 },
    penaltyNoteKeys: ["statutory.notes.it_234bc"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 23,
    promptEnabled: true,
  },
  {
    id: "it_presumptive_mar",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_presumptive_mar.title",
    applicabilityKey: "statutory.templates.it_presumptive_mar.applicability",
    bodyKey: "statutory.templates.it_presumptive_mar.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "advance_tax_instalment", instalmentMonth: 3, day: 15 },
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 24,
    promptEnabled: true,
  },
  {
    id: "it_itr_salaried",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_itr_salaried.title",
    applicabilityKey: "statutory.templates.it_itr_salaried.applicability",
    bodyKey: "statutory.templates.it_itr_salaried.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "annual_calendar", month: 7, day: 31 },
    penaltyNoteKeys: ["statutory.notes.it_234f"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 25,
    promptEnabled: true,
  },
  {
    id: "it_itr_business_non_audit",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_itr_business_non_audit.title",
    applicabilityKey: "statutory.templates.it_itr_business_non_audit.applicability",
    bodyKey: "statutory.templates.it_itr_business_non_audit.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "annual_calendar", month: 8, day: 31 },
    penaltyNoteKeys: ["statutory.notes.it_234f"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 26,
    promptEnabled: true,
  },
  {
    id: "it_itr_audit",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_itr_audit.title",
    applicabilityKey: "statutory.templates.it_itr_audit.applicability",
    bodyKey: "statutory.templates.it_itr_audit.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "annual_calendar", month: 10, day: 31 },
    penaltyNoteKeys: ["statutory.notes.it_234f"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 27,
    promptEnabled: true,
  },
  {
    id: "it_tax_audit_report",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_tax_audit_report.title",
    applicabilityKey: "statutory.templates.it_tax_audit_report.applicability",
    bodyKey: "statutory.templates.it_tax_audit_report.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "annual_calendar", month: 9, day: 30 },
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 28,
    promptEnabled: true,
  },
  {
    id: "it_itr_transfer_pricing",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_itr_transfer_pricing.title",
    applicabilityKey: "statutory.templates.it_itr_transfer_pricing.applicability",
    bodyKey: "statutory.templates.it_itr_transfer_pricing.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "annual_calendar", month: 11, day: 30 },
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 29,
    promptEnabled: true,
  },
  {
    id: "it_tp_report_92e",
    category: "IncomeTax",
    titleKey: "statutory.templates.it_tp_report_92e.title",
    applicabilityKey: "statutory.templates.it_tp_report_92e.applicability",
    bodyKey: "statutory.templates.it_tp_report_92e.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "annual_calendar", month: 10, day: 31 },
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 30,
    promptEnabled: true,
  },

  // —— TDS/TCS (21–25) ——
  {
    id: "tds_monthly_deposit",
    category: "TDS_TCS",
    titleKey: "statutory.templates.tds_monthly_deposit.title",
    applicabilityKey: "statutory.templates.tds_monthly_deposit.applicability",
    bodyKey: "statutory.templates.tds_monthly_deposit.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "tds_monthly_deposit", day: 7 },
    penaltyNoteKeys: ["statutory.notes.tds_interest"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 40,
    promptEnabled: true,
  },
  {
    id: "tds_return_q1",
    category: "TDS_TCS",
    titleKey: "statutory.templates.tds_return_q1.title",
    applicabilityKey: "statutory.templates.tds_return.applicability",
    bodyKey: "statutory.templates.tds_return_q1.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "tds_quarterly_return", quarterEnds: [6], day: 31, month: 7 },
    penaltyNoteKeys: ["statutory.notes.tds_234e"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 41,
    promptEnabled: true,
  },
  {
    id: "tds_return_q2",
    category: "TDS_TCS",
    titleKey: "statutory.templates.tds_return_q2.title",
    applicabilityKey: "statutory.templates.tds_return.applicability",
    bodyKey: "statutory.templates.tds_return_q2.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "tds_quarterly_return", quarterEnds: [9], day: 31, month: 10 },
    penaltyNoteKeys: ["statutory.notes.tds_234e"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 42,
    promptEnabled: true,
  },
  {
    id: "tds_return_q3",
    category: "TDS_TCS",
    titleKey: "statutory.templates.tds_return_q3.title",
    applicabilityKey: "statutory.templates.tds_return.applicability",
    bodyKey: "statutory.templates.tds_return_q3.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "tds_quarterly_return", quarterEnds: [12], day: 31, month: 1 },
    penaltyNoteKeys: ["statutory.notes.tds_234e"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 43,
    promptEnabled: true,
  },
  {
    id: "tds_return_q4",
    category: "TDS_TCS",
    titleKey: "statutory.templates.tds_return_q4.title",
    applicabilityKey: "statutory.templates.tds_return.applicability",
    bodyKey: "statutory.templates.tds_return_q4.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "tds_quarterly_return", quarterEnds: [3], day: 31, month: 5 },
    penaltyNoteKeys: ["statutory.notes.tds_234e"],
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 44,
    promptEnabled: true,
  },
  {
    id: "tds_certificate_note",
    category: "TDS_TCS",
    titleKey: "statutory.templates.tds_certificate_note.title",
    applicabilityKey: "statutory.templates.tds_certificate_note.applicability",
    bodyKey: "statutory.templates.tds_certificate_note.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "reference_only" },
    enabled: true,
    priority: 95,
    promptEnabled: false,
    attachedToTemplateId: "tds_return_q1",
  },

  // —— LLP (26–30) ——
  {
    id: "llp_form11",
    category: "LLP",
    titleKey: "statutory.templates.llp_form11.title",
    applicabilityKey: "statutory.templates.llp_form11.applicability",
    bodyKey: "statutory.templates.llp_form11.body",
    cautionKey: "statutory.caution.mca",
    dueRule: { kind: "annual_calendar", month: 5, day: 30 },
    penaltyNoteKeys: ["statutory.notes.llp_late_fee"],
    sourceNoteKey: "statutory.source.mca",
    enabled: true,
    priority: 50,
    promptEnabled: true,
  },
  {
    id: "llp_form8",
    category: "LLP",
    titleKey: "statutory.templates.llp_form8.title",
    applicabilityKey: "statutory.templates.llp_form8.applicability",
    bodyKey: "statutory.templates.llp_form8.body",
    cautionKey: "statutory.caution.mca",
    dueRule: { kind: "annual_calendar", month: 10, day: 30 },
    penaltyNoteKeys: ["statutory.notes.llp_late_fee"],
    sourceNoteKey: "statutory.source.mca",
    enabled: true,
    priority: 51,
    promptEnabled: true,
  },
  {
    id: "llp_audit_threshold",
    category: "LLP",
    titleKey: "statutory.templates.llp_audit_threshold.title",
    applicabilityKey: "statutory.templates.llp_audit_threshold.applicability",
    bodyKey: "statutory.templates.llp_audit_threshold.body",
    cautionKey: "statutory.caution.mca",
    dueRule: { kind: "reference_only" },
    enabled: true,
    priority: 96,
    promptEnabled: false,
  },
  {
    id: "llp_itr_non_audit",
    category: "LLP",
    titleKey: "statutory.templates.llp_itr_non_audit.title",
    applicabilityKey: "statutory.templates.llp_itr.applicability",
    bodyKey: "statutory.templates.llp_itr_non_audit.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "annual_calendar", month: 8, day: 31 },
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 52,
    promptEnabled: true,
  },
  {
    id: "llp_itr_audit",
    category: "LLP",
    titleKey: "statutory.templates.llp_itr_audit.title",
    applicabilityKey: "statutory.templates.llp_itr.applicability",
    bodyKey: "statutory.templates.llp_itr_audit.body",
    cautionKey: "statutory.caution.income_tax",
    dueRule: { kind: "annual_calendar", month: 10, day: 31 },
    sourceNoteKey: "statutory.source.income_tax",
    enabled: true,
    priority: 53,
    promptEnabled: true,
  },
];

const templateMap = new Map(STATUTORY_INFO_REGISTRY.map((t) => [t.id, t]));

export function getStatutoryTemplate(id: string): StatutoryInfoTemplate | undefined {
  return templateMap.get(id);
}

export function getEnabledStatutoryTemplates(): StatutoryInfoTemplate[] {
  return STATUTORY_INFO_REGISTRY.filter((t) => t.enabled);
}

export function getAttachedNotes(templateId: string): StatutoryInfoTemplate[] {
  return STATUTORY_INFO_REGISTRY.filter(
    (t) => t.attachedToTemplateId === templateId && t.enabled
  );
}
